name: publish
on:
  push:
    branches: [ main ]

jobs:
  publish-soup-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.REGISTRY_TOKEN }}

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Build Docker image
      run: |
        docker build . --tag ghcr.io/Redline-Hosting/ping:${{ steps.extract_branch.outputs.branch }}
        docker push ghcr.io/Redline-Hosting/ping:${{ steps.extract_branch.outputs.branch }}
